server:
  port: 8001
spring:
  application:
    name: SpringCloudStudy
  datasource:
    url: jdbc:mysql:///springcloud?serverTimezone=UTC
    username:
    password:
    name: defaultDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl