server:
  port: 8002
spring:
  application:
    name: cloud-payment-provider
  datasource:
    url: jdbc:mysql://43.139.80.148/springcloud?serverTimezone=UTC
    username: jjking
    password: 153359157aA@
    name: defaultDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7002/eureka,http://eureka7002.com:7003/eureka  # 集群版